class_name SituationRegistryID extends RefCounted
# Indonesian translation pack for SituationRegistry. Keyed by situation id.
# Choices appear in the SAME ORDER as the French canonical templates.

static func pack() -> Dictionary:
	return {
		&"inscription": {
			"title": "Batu yang dipenuhi tanda-tanda.",
			"choices": [
				{"text": "Kau menelusuri tanda-tanda itu dengan jarimu.",
				 "good_narr": "Sebuah kata purba menyala dalam dirimu. Kini kau tahu sesuatu yang baru.",
				 "bad_narr": "Tanda itu menjawabmu. Sesuatu telah tertulis di kulitmu."},
				{"text": "Kau membisikkan tanda-tanda itu dengan suara lirih.",
				 "good_narr": "Batu itu bergetar. Kau menerima lebih dari yang kau berikan.",
				 "bad_narr": "Sesuatu telah mendengarmu. Seharusnya tidak kau lakukan."},
				{"text": "Kau berlalu tanpa menyentuhnya.",
				 "good_narr": "Kau pergi dalam diam. Sesuatu mengikutimu dengan tatapan, tanpa bergerak.",
				 "bad_narr": "Tanda itu memanggilmu di luar kehendakmu. Kau memalingkan mata tepat waktu."},
			]},
		&"collapse": {
			"title": "Tanah runtuh di bawah kakimu.",
			"choices": [
				{"text": "Kau melompat ke tepian, terukur.",
				 "good_narr": "Kau mendarat dengan selamat. Napasmu kembali.",
				 "bad_narr": "Kau meleset dari tepian. Sesuatu berderak di lenganmu."},
				{"text": "Kau menerjang sebelum semuanya ambruk.",
				 "good_narr": "Kau menyeberang tepat saat batu itu runtuh. Kau masih berlari setelahnya.",
				 "bad_narr": "Tepian tajam merobek pahamu saat kau lewat."},
				{"text": "Kau menurunkan diri untuk melihat apa yang ada di bawah.",
				 "good_narr": "Di bawah lorong itu kau menemukan sesuatu yang berguna.",
				 "bad_narr": "Dasarnya lebih dalam dari dugaan. Kau memanjat naik dengan tenaga terkuras."},
			]},
		&"shrine": {
			"title": "Altar yang terlupakan, masih hangat.",
			"choices": [
				{"text": "Kau meletakkan tangan di atas batu, dalam diam.",
				 "good_narr": "Kehangatan mengalir. Salah satu lukamu menutup dengan rapi.",
				 "bad_narr": "Tidak terjadi apa-apa. Altar ini sudah menerima lebih dari yang bisa ia kembalikan."},
				{"text": "Kau mempersembahkan setetes darah ke alur batu.",
				 "good_narr": "Sesuatu menerima. Dunia terasa lebih jernih bagimu.",
				 "bad_narr": "Sesuatu menerima terlalu rakus. Kau merasakan beban yang baru."},
				{"text": "Kau menghancurkan batu itu dengan satu pukulan.",
				 "good_narr": "Di bawah batu, sebuah serpihan berguna. Kau mengantonginya.",
				 "bad_narr": "Di bawah batu, sebuah mata. Ia menatapmu. Kau mundur."},
			]},
		&"stranger": {
			"title": "Sosok bertudung mengulurkan sebuah kantong uang.",
			"choices": [
				{"text": "Kau menerima pemberian itu sambil berterima kasih.",
				 "good_narr": "Kantong itu berisi tepat apa yang kau butuhkan.",
				 "bad_narr": "Kantong itu sebuah hadiah. Perjanjiannya tak pernah tertulis."},
				{"text": "Kau menyambar kantong itu dan kabur.",
				 "good_narr": "Kau lenyap membawa apa yang ia ulurkan. Tak ada yang berteriak.",
				 "bad_narr": "Sesuatu menghantam punggungmu saat kau melarikan diri."},
				{"text": "Kau menolak dengan sopan dan berlalu.",
				 "good_narr": "Sosok itu membungkuk dan menghilang ke dalam kabut.",
				 "bad_narr": "Saat kau menoleh, ia sudah tak ada. Kau tak yakin ia pernah ada."},
			]},
		&"storm": {
			"title": "Badai menerjangmu, brutal.",
			"choices": [
				{"text": "Kau berlindung di bawah cadas yang menjorok.",
				 "good_narr": "Kau menunggu sampai reda. Dunia berbau basah dan hangus.",
				 "bad_narr": "Badai itu bertahan lebih lama dari kesabaranmu."},
				{"text": "Kau berjalan menembusnya, kepala tertunduk.",
				 "good_narr": "Kau keluar basah kuyup tapi lebih keras.",
				 "bad_narr": "Hujan es merobek bibirmu, alismu, kulitmu."},
				{"text": "Kau mengangkat kedua lengan dan memanggil angin.",
				 "good_narr": "Angin mendengarkanmu. Sekejap saja. Tapi ia mendengarkan.",
				 "bad_narr": "Angin menjawabmu. Ia menyebut namamu."},
			]},
		&"blood_trail": {
			"title": "Jejak darah segar mengarah ke pepohonan.",
			"choices": [
				{"text": "Kau mengikuti jejak itu, tanpa suara.",
				 "good_narr": "Di ujungnya, mayat yang masih segar. Dan sesuatu yang berguna padanya.",
				 "bad_narr": "Di ujungnya, makhluk yang berdarah itu. Masih hidup. Jahat."},
				{"text": "Kau menghapus jejak agar tak ada yang mengikutimu.",
				 "good_narr": "Tak ada yang akan menemukanmu di sini. Itu hal yang baik.",
				 "bad_narr": "Menghapus jejak butuh waktu. Terlalu lama."},
				{"text": "Kau mengambil arah yang berlawanan.",
				 "good_narr": "Kau menjauh. Jauh kemudian, kau mendengar sesuatu melolong di sana.",
				 "bad_narr": "Kau menjauh. Tapi jejak itu kini juga ada di depanmu."},
			]},
		&"deep_well": {
			"title": "Sumur yang digali lurus ke dalam batu. Airnya tak bergerak.",
			"choices": [
				{"text": "Kau membungkuk di tepinya. Kau melihat bayanganmu — lalu sesuatu yang lain.",
				 "good_narr": "Wajah yang lain itu memberitahumu apa yang perlu kau ketahui, lalu lenyap.",
				 "bad_narr": "Wajah yang lain itu tersenyum padamu. Kau mundur. Terlambat."},
				{"text": "Kau membisikkan namamu ke dalam sumur.",
				 "good_narr": "Sumur menjawab dengan suaramu sendiri, lebih muda. Napas lama kembali padamu.",
				 "bad_narr": "Sumur menjawab dengan suaramu, tapi ia mengucapkan hal lain dari yang kau katakan."},
				{"text": "Kau melempar batu dan mendengarkan dasarnya.",
				 "good_narr": "Kau menghitung lama. Kau tahu kedalamannya. Kau pergi dengan tenang.",
				 "bad_narr": "Kau tak pernah mendengar batu itu menyentuh dasar."},
			]},
		&"beggar_child": {
			"title": "Seorang anak duduk di jalan. Kurus. Membisu.",
			"choices": [
				{"text": "Kau memberinya separuh bekalmu.",
				 "good_narr": "Ia menatapmu tanpa bicara. Kelak, kau menemukan sekeping uang di sakumu yang tak pernah kau punya.",
				 "bad_narr": "Ia melahap semuanya dalam diam lalu kabur. Kau sadar apa yang baru saja kau lepaskan."},
				{"text": "Kau menanyakan namanya — dan menggeledah buntalannya.",
				 "good_narr": "Kau menemukan sesuatu yang berharga. Anak itu menangis tapi tak mengikutimu.",
				 "bad_narr": "Anak itu mengangkat matanya. Mata itu terlalu tua. Jauh terlalu tua."},
				{"text": "Kau pura-pura tak melihatnya dan berlalu.",
				 "good_narr": "Kau berlalu. Kau tak lebih baik dan tak lebih buruk dari sebelumnya.",
				 "bad_narr": "Kau merasakan tatapannya di tengkukmu selama berkilo-kilo jauhnya."},
			]},
		&"crossroads": {
			"title": "Jalan bercabang. Di kiri, keheningan. Di kanan, kicau burung.",
			"choices": [
				{"text": "Kau menuju keheningan.",
				 "good_narr": "Kau menemukan sesuatu yang tak pernah dimaksudkan untuk kau temukan.",
				 "bad_narr": "Keheningan itu bukan keheningan. Itu sebuah penantian."},
				{"text": "Kau menuju kicau burung.",
				 "good_narr": "Kau berjalan dalam nyanyian. Jalan ini aman, untuk hari ini.",
				 "bad_narr": "Burung-burung mendadak berhenti. Bukan untukmu mereka bernyanyi."},
				{"text": "Kau memejamkan mata dan mengikuti apa yang menarik dari dalam dirimu.",
				 "good_narr": "Kau mengambil jalan ketiga — yang hanya terlihat saat mata terpejam.",
				 "bad_narr": "Kau berjalan lama. Kau kembali ke persimpangan yang sama. Tiga kali."},
			]},
		&"burning_tree": {
			"title": "Sebatang pohon terbakar. Tanpa asap. Tanpa panas.",
			"choices": [
				{"text": "Kau menyentuh kulit kayunya. Api itu melintas menembus tubuhmu.",
				 "good_narr": "Pengetahuan tua mengalir melintasimu. Kau takkan berani membaginya.",
				 "bad_narr": "Api itu memang menembusmu. Tapi ia meninggalkan sesuatu saat lewat."},
				{"text": "Kau menebang pohon itu. Apinya padam seketika.",
				 "good_narr": "Pohon itu tumbang tanpa suara. Api padam. Dunia terasa lebih sederhana.",
				 "bad_narr": "Pohon itu berdarah. Bukan getah. Darah. Ia menghantammu saat rubuh."},
				{"text": "Kau memalingkan muka dan terus berjalan.",
				 "good_narr": "Kau pergi. Kelak, kau tak lagi bisa memastikan pernah benar-benar melihatnya.",
				 "bad_narr": "Kau pergi. Pohon itu berjalan di belakangmu selama enam langkah. Kau tak berani menoleh."},
			]},
		&"warm_carcass": {
			"title": "Bangkai yang masih hangat. Tak ada jejak di sekitarnya.",
			"choices": [
				{"text": "Kau memeriksa luka-lukanya. Yang membunuh ini bukan binatang.",
				 "good_narr": "Kau memahami sesuatu tentang si pembunuh. Mungkin kau bisa menghindarinya.",
				 "bad_narr": "Kau memahami sesuatu tentang si pembunuh. Seharusnya tidak."},
				{"text": "Kau mengambil dagingnya. Persetan dengan sisanya.",
				 "good_narr": "Kau makan. Kau melanjutkan jalan dengan tubuh lebih kokoh. Memang itu yang dibutuhkan.",
				 "bad_narr": "Kau makan. Sesuatu dalam daging itu seharusnya tak pernah dimakan."},
				{"text": "Kau pergi tanpa menyentuh. Kau pergi cepat.",
				 "good_narr": "Kau pergi. Mungkin itu keputusan terbaikmu hari ini.",
				 "bad_narr": "Kau pergi. Sesuatu mengawasimu dari pohon di dekat sana."},
			]},
		&"the_double": {
			"title": "Di ujung jalan, seseorang. Ia memakai wajahmu.",
			"choices": [
				{"text": "Kau menyerangnya tanpa ragu. Tak ada tempat untuk dua dirimu.",
				 "good_narr": "Kau memukulnya. Ia remuk seperti kaca hitam. Kau membawa satu pecahannya.",
				 "bad_narr": "Kau memukul wajahmu sendiri. Kau merasakan sayatannya di wajahmu."},
				{"text": "Kau mengajaknya bicara. Kau bertanya siapa dia.",
				 "good_narr": "Ia menjawab pelan. Ia mengajarimu sesuatu yang telah kau lupakan.",
				 "bad_narr": "Ia mengulang setiap katamu, terbalik. Lalu ia mengambil bayanganmu."},
				{"text": "Kau memalingkan mata dan lewat jauh darinya.",
				 "good_narr": "Kau lewat. Ia tetap di sana, tak bergerak. Kau tak menoleh.",
				 "bad_narr": "Kau lewat. Kau merasa ia telah mengambil tempatmu di jalan yang baru saja kau tinggalkan."},
			]},
		&"broken_statue": {
			"title": "Patung pecah setengah terkubur. Wajahnya hilang.",
			"choices": [
				{"text": "Kau menegakkan apa yang bisa. Kau membersihkan batunya.",
				 "good_narr": "Kau melakukan hal kecil yang benar. Sesuatu dalam dirimu kembali sejajar.",
				 "bad_narr": "Kau bekerja lama. Kau lupa untuk apa. Kau tak mendapat apa-apa."},
				{"text": "Kau menggeledah alasnya. Patung sering menyembunyikan sesuatu.",
				 "good_narr": "Kau menemukan rongga. Di dalamnya, sesuatu yang ditinggalkan untukmu.",
				 "bad_narr": "Kau menemukan rongga. Sesuatu pernah ada di sana. Kini ia mengikutimu."},
				{"text": "Kau menempelkan dahimu ke batu. Kau mendengarkan.",
				 "good_narr": "Batu itu menceritakan perang yang pernah disaksikannya. Itu sudah lama sekali.",
				 "bad_narr": "Batu itu mengingat. Ia ingin kau juga mengingat."},
			]},
		&"buried_pilgrim": {
			"title": "Tulang-belulang setengah terkubur masih menggenggam sebuah liontin.",
			"choices": [
				{"text": "Kau menggali liontin itu. Ia hangat.",
				 "good_narr": "Liontin itu membangunkan pengetahuan purba. Kau mengerti mengapa ia berjalan ke sini.",
				 "bad_narr": "Liontin itu terbuka. Sesuatu di dalamnya menatapmu sebelum kau menutupnya kembali."},
				{"text": "Kau mengucapkan berkat dan membiarkan semuanya di tempat.",
				 "good_narr": "Kedamaian melintasimu. Satu ketakutanmu berkurang.",
				 "bad_narr": "Kata-katamu tersesat. Kau berdoa terlalu lama. Dingin mencengkerammu."},
				{"text": "Kau merenggut liontin itu dengan satu sentakan.",
				 "good_narr": "Kau mendapatkannya. Beratnya melebihi ukurannya.",
				 "bad_narr": "Akar patah menggores lenganmu. Mungkin itu bukan akar."},
			]},
		&"iron_door": {
			"title": "Pintu besi tersegel berdiri tegak, di tempat yang seharusnya kosong.",
			"choices": [
				{"text": "Kau membenturkan bahu ke pintu. Sekali. Lagi.",
				 "good_narr": "Kuncinya jebol. Di baliknya: kehampaan yang berbau emas. Kau pergi dengan beban penuh.",
				 "bad_narr": "Sesuatu di lenganmu patah lebih dulu daripada pintunya."},
				{"text": "Kau menempelkan telapak dan mendengarkan apa yang tidur di baliknya.",
				 "good_narr": "Yang tidur di baliknya menitipkan sebuah nama. Kau menyimpannya.",
				 "bad_narr": "Yang tidur di baliknya telah terjaga. Ia mengikutimu, mulai sekarang."},
				{"text": "Kau berbalik tanpa menyentuh pintu itu.",
				 "good_narr": "Kau pergi. Pintu itu sudah tak ada saat kau menoleh. Syukurlah.",
				 "bad_narr": "Kau pergi. Tapi kau tahu kau akan kembali. Kau bahkan sudah tahu kapan."},
			]},
		&"wounded_merc": {
			"title": "Seorang tentara bayaran terluka mengulurkan tangan padamu.",
			"choices": [
				{"text": "Kau berlutut dan membalut lukanya.",
				 "good_narr": "Ia menyerahkan bilahnya sebelum memejamkan mata. Kau mendapat lebih dari yang kau kira.",
				 "bad_narr": "Saat membungkuk, kau tergelincir. Bilahnya jatuh dan menggores pahamu."},
				{"text": "Kau menggeledah sakunya sambil bicara lembut padanya.",
				 "good_narr": "Kau menemukan tiga keping uang, sebuah peta, sebuah segel. Ia tak melihat apa-apa.",
				 "bad_narr": "Tangannya mencengkeram pergelanganmu, lebih kuat dari seharusnya. Ia membisikkan satu kata."},
				{"text": "Kau mengakhiri penderitaannya dengan satu tebasan bersih.",
				 "good_narr": "Itu hal yang benar untuk dilakukan. Kau membawa cincinnya.",
				 "bad_narr": "Matanya tak melepaskanmu. Kau masih melihatnya saat memejamkan matamu sendiri."},
			]},
		&"cold_fork": {
			"title": "Dua jalan. Angin hanya bertiup lewat salah satunya.",
			"choices": [
				{"text": "Kau mengambil yang berangin. Kau ingin tahu dari mana angin itu datang.",
				 "good_narr": "Di ujungnya, sebuah tebing pandang yang sunyi. Kau memahami hal yang seharusnya tak dipahami siapa pun.",
				 "bad_narr": "Di ujungnya, yang meniupkan angin itu. Ia punya mulut. Ia melihatmu."},
				{"text": "Kau mengambil yang satunya. Tanpa angin, tanpa kejutan.",
				 "good_narr": "Jalannya lembut. Tenagamu pulih.",
				 "bad_narr": "Jalan itu begitu tenang sampai kau ragu pernah memilihnya. Kau berjalan lama."},
				{"text": "Kau mengajukan pertanyaan pada persimpangan, dengan suara keras.",
				 "good_narr": "Persimpangan menjawabmu — di satu sisi, lewat angin; di sisi lain, lewat keheningan. Kau tahu mana yang harus diambil.",
				 "bad_narr": "Persimpangan telah mendengarmu. Ia menawarkan jalan ketiga. Kau keluar dari sana, kemudian, tanpa ingatan tentang apa yang ada di dalamnya."},
			]},
		&"caged_beast": {
			"title": "Serigala terluka, terkurung dalam kandang besi. Jerujinya berkarat.",
			"choices": [
				{"text": "Kau bicara lembut padanya, sambil mempelajari mekanismenya.",
				 "good_narr": "Serigala itu pergi tanpa menggeram. Mungkin suatu hari ia kembali membelamu.",
				 "bad_narr": "Kau mendekat terlalu jauh. Rahangnya mengatup, lebih cepat dari tanganmu."},
				{"text": "Kau menghantam kandang itu dengan batu.",
				 "good_narr": "Kandang itu jebol. Serigala kabur. Kau menemukan beberapa keping uang di perangkapnya.",
				 "bad_narr": "Batu itu memantul. Sesuatu di pergelanganmu patah sebelum kandangnya."},
				{"text": "Kau berlalu. Ini bukan pertarunganmu.",
				 "good_narr": "Serigala itu mengikutimu dengan tatapan. Kau tak tahu itu dendam atau kenangan.",
				 "bad_narr": "Kelak, di tengah malam, kau mendengar lolongan. Lolongan itu menyebut namamu."},
			]},
		&"burning_library": {
			"title": "Perpustakaan yang runtuh. Beberapa buku masih berasap. Selembar halaman utuh melayang ke arahmu.",
			"choices": [
				{"text": "Kau menangkap halaman itu dan membacanya sebelum padam.",
				 "good_narr": "Tiga kata. Sebuah nama. Sebuah tanggal. Kini kau tahu sesuatu yang telah dilupakan orang-orang hidup.",
				 "bad_narr": "Kata-kata itu masuk ke kulitmu dan menetap. Mereka berdarah setiap kau berpikir."},
				{"text": "Kau bergegas menyelamatkan buku-buku lain.",
				 "good_narr": "Kau keluar membawa separuh isi rak, hangus tapi kaya.",
				 "bad_narr": "Atapnya runtuh. Kau keluar merangkak, punggung tercabik."},
				{"text": "Kau membiarkan abu bicara padamu.",
				 "good_narr": "Suara-suara melintasimu dan meringankanmu. Sebuah kutukan pergi bersama asap.",
				 "bad_narr": "Seribu suara meneriakkan kata yang sama padamu. Kata itu bukan milikmu."},
			]},
		&"ferryman": {
			"title": "Tukang perahu yang bisu mengulurkan tangan. Perahunya tak benar-benar menyentuh air.",
			"choices": [
				{"text": "Kau membayar dengan uang, sopan, tanpa bertanya.",
				 "good_narr": "Seberang tiba lebih cepat dari dugaan. Kau menghemat waktu.",
				 "bad_narr": "Saat kakimu menjejak tanah, ada yang hilang dalam dirimu. Mungkin setahun."},
				{"text": "Kau menyelipkan kepingan timah yang dicat.",
				 "good_narr": "Ia tersenyum, menyimpan kepingan itu tanpa melihat. Kau pergi lebih kaya.",
				 "bad_narr": "Ia menoleh di tengah air. Ia tahu setiap kebohonganmu."},
				{"text": "Kau menawarkan namamu sebagai ganti uang.",
				 "good_narr": "Ia menerima. Kau menyeberang, ringan tanpa satu nama. Masih ada nama-nama lain bagimu.",
				 "bad_narr": "Ia mengambil nama itu dan menyimpannya. Akibatnya akan kau ingat kelak."},
			]},
		&"hanging_cage": {
			"title": "Kandang tergantung di pohon. Seorang lelaki di dalamnya. Hidup.",
			"choices": [
				{"text": "Kau bertanya padanya: mengapa.",
				 "good_narr": "Ia mengajarimu tiga hal tentang tanah ini yang tak kau ketahui.",
				 "bad_narr": "Ia tertawa, lama. Tawa itu tak bisa kau lupakan."},
				{"text": "Kau memotong talinya.",
				 "good_narr": "Ia terjerembap, berterima kasih, menyerahkan sebuah cincin, lalu kabur.",
				 "bad_narr": "Kandang itu jatuh. Menimpamu. Lengan lelaki itu juga."},
				{"text": "Kau berbalik sebelum ia melihatmu.",
				 "good_narr": "Kau pergi dalam diam. Ia tak bergerak.",
				 "bad_narr": "Kau melihatnya menatapmu dalam mimpimu, malam itu."},
			]},
		&"path_doll": {
			"title": "Boneka anak-anak, terduduk tegak di tengah jalan. Matanya dilukis.",
			"choices": [
				{"text": "Kau membungkuk untuk memeriksanya.",
				 "good_narr": "Di bawah boneka, pintu kecil. Di bawah pintu, sesuatu yang berguna.",
				 "bad_narr": "Mata itu berkedip. Sekali. Kau pergi. Kau menoleh. Ia sudah tak ada."},
				{"text": "Kau menginjaknya saat lewat.",
				 "good_narr": "Tidak ada apa-apa. Hanya derak porselen.",
				 "bad_narr": "Sesuatu menjerit di kepalamu. Suara anak kecil. Suaramu, mungkin."},
				{"text": "Kau menyebut namanya — nama yang tak pernah kau pelajari.",
				 "good_narr": "Boneka itu membungkuk pelan. Sebuah ketakutan lama meninggalkanmu.",
				 "bad_narr": "Kau menyebut nama yang benar. Kini ia tahu namamu."},
			]},
		&"bear_trap": {
			"title": "Perangkap beruang, rahang terbuka. Masih ada darah di atasnya, segar.",
			"choices": [
				{"text": "Kau memutarinya sambil menandai tempatnya.",
				 "good_narr": "Kau belajar membaca jejak semacam ini. Kau akan menghindari yang lain.",
				 "bad_narr": "Kau yakin akan mengingatnya. Kau hanya mengingatnya setengah."},
				{"text": "Kau melumpuhkannya dengan sebatang dahan untuk memeriksanya.",
				 "good_narr": "Mekanismenya cerdik. Kau belajar membuatnya sendiri.",
				 "bad_narr": "Dahan itu patah lebih cepat dari dugaan. Perangkap menggigit lengan bawahmu."},
				{"text": "Kau memicu perangkap itu dengan satu tendangan.",
				 "good_narr": "Berisik tapi aman. Kau pergi tanpa cedera.",
				 "bad_narr": "Serpihan logam menyayat pahamu."},
			]},
		&"echo_cave": {
			"title": "Mulut batu. Di dalamnya, gemamu sendiri menjawab terlambat satu detik.",
			"choices": [
				{"text": "Kau meneriakkan namamu. Kau mendengarkan apa yang dikembalikan.",
				 "good_narr": "Gema menyebut namamu — lalu tiga nama lain. Kau mengerti siapa yang telah kau lupakan.",
				 "bad_narr": "Gema menyebut namamu — lalu nama kematianmu. Kau mengingatnya di luar kehendakmu."},
				{"text": "Kau menyanyikan keheningan — empat nada yang tak pernah diajarkan siapa pun.",
				 "good_narr": "Gua itu mengulang nyanyianmu. Sesuatu dalam dirimu terurai lega.",
				 "bad_narr": "Nyanyian itu berlanjut setelah kau diam. Kau pergi dengan tenaga terkuras."},
				{"text": "Kau meneriakkan nama palsu untuk melihat apakah gua mengikutinya.",
				 "good_narr": "Ia mengikuti. Kau tahu kini ia bodoh. Itu berharga untuk diketahui.",
				 "bad_narr": "Ia tak mengikuti. Ia meneriakkan nama yang asli. Lalu terkekeh."},
			]},
		&"ancient_gate": {
			"title": "Gerbang batu tanpa pintu. Di sisi seberangnya, pemandangan tidak sama.",
			"choices": [
				{"text": "Kau melintasinya.",
				 "good_narr": "Kau kembali dari sisi yang sama, kemudian. Kau tahu sesuatu. Kau takkan pernah bisa mengatakannya.",
				 "bad_narr": "Kau kembali, tapi dengan cara lain. Sesuatu mengikutimu, di punggungmu, setengah langkah di belakang."},
				{"text": "Kau melempar kerikil dan menunggu.",
				 "good_narr": "Kerikil itu tak kembali. Kau tahu cukup. Kau pergi.",
				 "bad_narr": "Kerikil itu kembali — panas. Kau pergi cepat, tapi tak cukup cepat."},
				{"text": "Kau meletakkan tangan pada gerbang itu.",
				 "good_narr": "Sesuatu yang sangat tua menjawabmu. Kau pergi lebih ringan.",
				 "bad_narr": "Sesuatu yang sangat tua mengenalmu, mulai sekarang."},
			]},
		&"lost_letter": {
			"title": "Sepucuk surat bernoda hujan, masih terbaca. Tulisannya gemetar. Surat itu dialamatkan padamu.",
			"choices": [
				{"text": "Kau membacanya sampai habis.",
				 "good_narr": "Seseorang, entah di mana, telah menebak kau akan datang ke sini.",
				 "bad_narr": "Surat itu darimu. Lebih tua. Berisi peringatan yang tak lagi bisa kau turuti."},
				{"text": "Kau merobeknya tanpa membaca.",
				 "good_narr": "Angin membawa sobekan-sobekan itu. Kau merasa lebih ringan.",
				 "bad_narr": "Tintanya melekat di jarimu. Isinya kau baca kemudian, dalam mimpi, tanpa bisa berhenti."},
				{"text": "Kau melipatnya kembali dan meletakkannya di atas batu, agar kembali pada yang tahu.",
				 "good_narr": "Tiga wilayah kemudian, seseorang mengulurkan sekeping uang. Untuk surat itu, katanya.",
				 "bad_narr": "Kau menghilangkannya di jalan. Seseorang pasti akan membacanya."},
			]},
		&"sleeping_giant": {
			"title": "Sosok raksasa tertidur di lereng bukit. Tanah naik dan turun mengikuti napasnya.",
			"choices": [
				{"text": "Kau memutar jauh, tanpa sedikit pun suara.",
				 "good_narr": "Kau lewat. Raksasa itu terus bernapas. Kau belajar bahwa tak semua ketakutan terbangun.",
				 "bad_narr": "Putaran itu lebih panjang dari kesabaranmu."},
				{"text": "Kau mendekat, untuk melihat wajahnya.",
				 "good_narr": "Wajahnya mirip wajahmu, lebih tua. Kau tahu jadi apa kau kelak, mungkin.",
				 "bad_narr": "Ia membuka satu mata. Ia menatapmu sedetik. Ia menutupnya. Tidurmu takkan pernah sama lagi."},
				{"text": "Kau membisikkan sebuah kata di dekat telinganya.",
				 "good_narr": "Ia tersenyum dalam tidurnya. Ia mengajarimu kata lain. Lebih besar.",
				 "bad_narr": "Ia mengajarimu sebuah kata. Kau takkan bisa mengucapkannya keras-keras tanpa membangunkannya."},
			]},
		&"cursed_coin": {
			"title": "Sekeping emas di cekungan batu. Berkilau seolah baru saja diletakkan.",
			"choices": [
				{"text": "Kau mengambilnya tanpa ragu.",
				 "good_narr": "Beratnya mengejutkan. Kau pergi lebih kaya. Untuk saat ini.",
				 "bad_narr": "Keping itu membakar telapakmu. Kini ia menyandang tandamu."},
				{"text": "Kau menatapnya lama tanpa menyentuh.",
				 "good_narr": "Kau belajar mengenali jebakan yang terlalu indah. Kau pergi.",
				 "bad_narr": "Kau pergi tanpa mengambilnya. Ia muncul di sakumu, kemudian."},
				{"text": "Kau menukarnya dengan keping lain.",
				 "good_narr": "Tipuanmu berhasil. Kau menyimpan yang asli. Orang berikutnya mengambil yang palsu.",
				 "bad_narr": "Kau kira sedang bermain. Kau hanya memilih jebakan yang lain."},
			]},
		&"whisper_dark": {
			"title": "Bisikan dalam kegelapan. Ia tahu namamu. Katanya ia punya satu pertanyaan untukmu.",
			"choices": [
				{"text": "Kau berkata padanya: tanyakanlah.",
				 "good_narr": "Pertanyaannya sederhana. Jawabannya sudah lama kau tahu. Kau mengucapkannya. Bisikan itu pergi, puas.",
				 "bad_narr": "Pertanyaannya tak punya jawaban. Kau mengarang satu. Ia tahu kau berbohong."},
				{"text": "Kau berteriak ke dalam gelap untuk menenggelamkannya.",
				 "good_narr": "Teriakanmu bertahan lebih lama dari miliknya. Kau pergi.",
				 "bad_narr": "Sesuatu menjawabmu, dua kali lebih keras. Kau pergi terhuyung."},
				{"text": "Kau pura-pura mati, tak bergerak.",
				 "good_narr": "Bisikan itu lewat di sampingmu. Kau belajar bahwa sebagian ketakutan tak punya bau.",
				 "bad_narr": "Ia mengitarimu, lama. Akhirnya ia menyentuh tengkukmu, sekilas."},
			]},
		&"snake_oil": {
			"title": "Pedagang di tepi jalan menawarkan botol kecil \"penyembuh segalanya\".",
			"choices": [
				{"text": "Kau menawar panjang lebar, berpura-pura tertarik.",
				 "good_narr": "Karena lelah, ia akhirnya melepas botol yang asli. Kau pergi membawa obat sungguhan.",
				 "bad_narr": "Ia bicara lebih banyak darimu, lama. Kau pergi kelelahan tanpa apa pun."},
				{"text": "Kau bertanya apa sebenarnya isinya.",
				 "good_narr": "Ia tertawa, memberimu barang asli yang ia simpan untuk dirinya. Satu luka menutup.",
				 "bad_narr": "Ia tersenyum, menyodorkan botol itu. Kau minum. Itu yang salah."},
				{"text": "Kau merebut satu botol dan pergi.",
				 "good_narr": "Ia tak mengejarmu. Botol yang asli kau temukan kemudian.",
				 "bad_narr": "Kau minum untuk meredakan haus. Kau menyadari kesalahanmu terlambat."},
			]},
		&"frozen_pool": {
			"title": "Kolam air membeku di tengah musim panas. Sesuatu bergerak, perlahan, di bawah es.",
			"choices": [
				{"text": "Kau memecahkan es dengan pukulan keras untuk melihat.",
				 "good_narr": "Di bawah es, seekor ikan, raksasa, tak bergerak. Kau pergi membawa satu sisik — berguna.",
				 "bad_narr": "Di bawah es, sebuah wajah. Terbuka. Menatapmu. Kau menutup lubang itu buru-buru."},
				{"text": "Kau memutarinya, tanpa memandang.",
				 "good_narr": "Dingin menyelimutimu lembut, membasuhmu. Kau pergi dengan tubuh segar.",
				 "bad_narr": "Putarannya lebih jauh dari dugaan. Kau berjalan lama."},
				{"text": "Kau meletakkan tangan di atas es dan mendengarkan.",
				 "good_narr": "Es itu menceritakan tiga musim dingin. Kau belajar lebih dari yang kau kira mungkin.",
				 "bad_narr": "Es itu meminum panas tubuhmu. Kau menarik tangan terlambat."},
			]},
		&"empty_shoes": {
			"title": "Sepasang sepatu kecil, berjajar rapi di tengah jalan. Tak ada siapa pun di sekitar.",
			"choices": [
				{"text": "Kau berbalik tanpa ragu.",
				 "good_narr": "Kau berjalan lama, tapi merasa lebih ringan karena lari dari kisah yang bukan milikmu.",
				 "bad_narr": "Kau berjalan lama. Terlalu lama."},
				{"text": "Kau mengubur sepatu itu di bawah batu, sambil membisikkan sebuah kata.",
				 "good_narr": "Kau pergi dengan damai. Di suatu tempat, sesuatu berterima kasih tanpa suara.",
				 "bad_narr": "Saat kau mengubur, kau mendengar langkah-langkah kecil di sekelilingmu."},
				{"text": "Kau memungutnya dan mencari pemiliknya.",
				 "good_narr": "Kau menemukan desa kecil yang ditinggalkan. Di sana, sesuatu yang berguna.",
				 "bad_narr": "Kau menemukan seorang anak berjalan tanpa alas kaki. Ia menatapmu. Kau tak bisa lagi lupa."},
			]},
		&"fallen_comet": {
			"title": "Serpihan membara jatuh dari langit. Tanah berasap di sekelilingnya. Ia bernapas, samar.",
			"choices": [
				{"text": "Kau memecahkannya untuk melihat isinya.",
				 "good_narr": "Di dalamnya, pecahan sekeras tulang, berkilau. Kau menyelipkannya ke saku.",
				 "bad_narr": "Ia meledak di tanganmu. Serpihan membara merobek telapakmu."},
				{"text": "Kau meletakkan tangan di atasnya untuk mendengar.",
				 "good_narr": "Ia menceritakan asalnya. Kini kau tahu nama sebuah bintang.",
				 "bad_narr": "Ia menuliskan namanya di kulitmu. Lukanya membakar lama."},
				{"text": "Kau menunggu sampai ia dingin sebelum memutuskan.",
				 "good_narr": "Kau pergi membawa pecahan yang suam, lebih mudah dibawa.",
				 "bad_narr": "Ia mendingin terlalu cepat. Tak ada lagi yang bisa ia berikan."},
			]},
		&"mad_vagabond": {
			"title": "Seorang gelandangan tertawa sendiri, bicara pada semak, menjawabnya pula. Ia menggenggam benda kecil berkilau.",
			"choices": [
				{"text": "Kau bertanya apa yang ia katakan pada semak itu.",
				 "good_narr": "Ia mengatakan hal yang takkan dikatakan siapa pun. Hal itu akan berguna bagimu.",
				 "bad_narr": "Ia mengatakan hal yang seharusnya tak dikatakan siapa pun. Kau telah mendengarnya."},
				{"text": "Kau mencuri benda kecil itu selagi ia tertawa.",
				 "good_narr": "Benda itu berguna. Ia bahkan tak menyadarinya.",
				 "bad_narr": "Ia berhenti tertawa. Ia menatapmu — jernih, sadar. Takkan pernah lagi kau mencurinya tanpa balasan."},
				{"text": "Kau berlalu tanpa memandangnya.",
				 "good_narr": "Kau pergi. Ia terus tertawa di belakangmu.",
				 "bad_narr": "Kau pergi. Tawanya berhenti di saat yang sama. Kau tak tahu kenapa."},
			]},
		&"charred_map": {
			"title": "Peta dengan tepian hangus. Peta tanah ini — dengan tanda-tanda yang tak pernah kau lihat.",
			"choices": [
				{"text": "Kau mempelajari tanda-tanda itu dengan saksama.",
				 "good_narr": "Kau mengenali satu tempat, mungkin dua. Kelak itu akan berguna.",
				 "bad_narr": "Kau menghabiskan terlalu banyak waktu. Hari memudar sebelum kau belajar apa pun."},
				{"text": "Kau menumpangkan peta itu ke tanah dengan gerakan ritual.",
				 "good_narr": "Tanah sedikit menyesuaikan diri dengan peta. Kau melihat sesuatu yang sebelumnya tak ada.",
				 "bad_narr": "Tanah menyesuaikan diri terlalu jauh. Sesuatu telah menunggu seseorang melakukan persis hal itu."},
				{"text": "Kau melipatnya dan menyimpannya di saku untuk nanti.",
				 "good_narr": "Kau memutuskan berpikir nanti. Mungkin kau takkan pernah kembali padanya.",
				 "bad_narr": "Kau lupa membacanya. Peta itu lenyap dari sakumu, setelahnya."},
			]},
		&"head_pole": {
			"title": "Kepala terpenggal tertancap di sebuah tiang. Matanya mengikuti pandanganmu saat kau bergerak.",
			"choices": [
				{"text": "Kau menanyakan namanya.",
				 "good_narr": "Ia menjawab. Ia menceritakan apa yang terjadi di sini. Kau akan tahu menghindari kesalahannya.",
				 "bad_narr": "Ia menyebut namamu. Bukan namanya. Kau pergi cepat."},
				{"text": "Kau menjatuhkannya dengan satu tendangan.",
				 "good_narr": "Ia menggelinding, terdiam. Kau pergi dengan tenang.",
				 "bad_narr": "Ia menggelinding sambil menjerit namamu. Kau masih mendengarnya kemudian."},
				{"text": "Kau meletakkan sekeping uang di mulutnya.",
				 "good_narr": "Ia terdiam. Sesuatu yang berat meninggalkanmu.",
				 "bad_narr": "Ia menelan keping itu dan meminta yang berikutnya. Dan berikutnya."},
			]},
		&"festival_lights": {
			"title": "Di ujung jalan yang lengang, lentera-lentera menyala bergoyang di atas meja-meja kosong. Tak ada suara.",
			"choices": [
				{"text": "Kau duduk di salah satu meja seolah kau memang ditunggu.",
				 "good_narr": "Seseorang menghidangkan piring yang tak kasatmata. Kau makan. Sesuatu yang purba melintasimu.",
				 "bad_narr": "Kau makan. Kau berdiri. Beberapa jam hilang dari ingatanmu."},
				{"text": "Kau menyambar satu lentera dan kabur cepat-cepat.",
				 "good_narr": "Kau pergi membawa lentera yang tak pernah padam.",
				 "bad_narr": "Lentera itu mengikutimu. Selamanya. Kau akan belajar tidur bersamanya."},
				{"text": "Kau memutar jauh, tanpa memasuki jalan itu.",
				 "good_narr": "Kau takkan pernah tahu apa yang terjadi di sana. Mungkin itu lebih baik.",
				 "bad_narr": "Kau akan memimpikan jalan itu. Sering."},
			]},
		&"breathing_earth": {
			"title": "Sepetak tanah naik dan turun, seperti dada yang tertidur. Pelan-pelan.",
			"choices": [
				{"text": "Kau menempelkan telapak dan menyelaraskan napasmu.",
				 "good_narr": "Tanah itu menenangkanmu. Sebuah ketakutan lama mereda.",
				 "bad_narr": "Napasmu mengambil napasnya. Kau pergi agak sakit — tanah itu, agaknya, membaik."},
				{"text": "Kau menancapkan bilahmu ke dalamnya untuk melihat.",
				 "good_narr": "Ia berdarah — sedikit. Kau pergi membawa segenggam tanah cokelat yang luar biasa.",
				 "bad_narr": "Ia berdarah — banyak. Darahnya tidak merah."},
				{"text": "Kau berjalan membuat lingkaran selebar mungkin mengitarinya.",
				 "good_narr": "Kau pergi. Setelahnya keheningan total.",
				 "bad_narr": "Lingkarannya lebih besar dari perkiraanmu. Kau berjalan sampai malam."},
			]},
		&"carriage_wreck": {
			"title": "Kereta kuda terguling, kudanya lenyap, sebuah peti terbuka. Kain masih beterbangan.",
			"choices": [
				{"text": "Kau menggeledah peti itu.",
				 "good_narr": "Kau menemukan cincin yang berguna dan surat yang menarik.",
				 "bad_narr": "Sesuatu di dalam peti menggigit tanganmu — perangkap mekanis yang masih hidup."},
				{"text": "Kau menata semuanya kembali seolah kau tak pernah datang.",
				 "good_narr": "Kau pergi membawa dua keping uang dan hati nurani yang bersih.",
				 "bad_narr": "Kau menata dengan rapi. Tapi kau melupakan sesuatu. Kau takkan tahu apa."},
				{"text": "Kau mencari kuda-kudanya lebih dulu.",
				 "good_narr": "Kau menemukan kuda terluka, merawatnya, dan pergi bersamanya.",
				 "bad_narr": "Kau tak menemukan mereka. Malam turun."},
			]},
		&"dreaming_fish": {
			"title": "Ikan raksasa terdampar di pasir, hidup. Ia tak meronta. Ia tidur. Ia bermimpi.",
			"choices": [
				{"text": "Kau menyentuh sisi tubuhnya dan bermimpi bersamanya sejenak.",
				 "good_narr": "Kau tahu apa yang dimimpikan makhluk yang tak pernah mengenal takut.",
				 "bad_narr": "Kau mengetahui mimpinya. Mimpi itu jadi milikmu. Kau tak lagi yakin sedang terjaga."},
				{"text": "Kau mendorongnya pelan-pelan ke arah air.",
				 "good_narr": "Ia setengah terbangun, menatapmu, lalu pergi. Kelak, kau menemukan hadiah di pantai.",
				 "bad_narr": "Ia lebih berat dari dugaanmu. Kau mengerahkan seluruh tenagamu."},
				{"text": "Kau mengambil sepotong dagingnya untuk dimakan.",
				 "good_narr": "Kau makan, kenyang, menyimpan sisanya.",
				 "bad_narr": "Dagingnya tak diperuntukkan bagi yang hidup. Kau muntah lama."},
			]},
		&"singing_crowns": {
			"title": "Tiga mahkota tersusun melingkar. Saat angin bertiup, mereka bernyanyi — masing-masing satu nada.",
			"choices": [
				{"text": "Kau mengiringi nyanyian mereka dengan suaramu.",
				 "good_narr": "Kau mempelajari nada keempat. Tak ada orang lain yang mengenalnya.",
				 "bad_narr": "Satu mahkota terdiam saat kau bernyanyi. Kini kau tahu yang mana."},
				{"text": "Kau mengambil satu dan pergi.",
				 "good_narr": "Berat. Tapi lebih ringan dari masa depanmu.",
				 "bad_narr": "Dua yang tersisa mulai menjerit-jeritkan namamu. Lama."},
				{"text": "Kau mengajukan satu pertanyaan pada mahkota-mahkota itu.",
				 "good_narr": "Mereka menjawab satu per satu. Kini kau tahu siapa yang pernah jadi raja di sini.",
				 "bad_narr": "Mereka menjawab serentak. Kau tak mengerti apa pun. Kau pergi."},
			]},
		&"night_fire": {
			"title": "Api unggun di tepi jalan. Seorang pengelana melambai: kemarilah, duduk.",
			"choices": [
				{"text": "Kau duduk. Kau mendengarkan apa yang ingin ia katakan.",
				 "good_narr": "Kalian berbagi roti dan tiga cerita. Kau pergi dengan sesuatu di perut dan di kepala.",
				 "bad_narr": "Roti yang ia ulurkan terasa aneh. Kau baru menyadarinya setelah menelannya."},
				{"text": "Kau menerima sambutannya, tapi tidur dengan tangan di belatimu.",
				 "good_narr": "Kau bangun lebih dulu. Ia masih tidur. Kau mengambil apa yang kau suka dari tasnya.",
				 "bad_narr": "Ia bangun lebih dulu. Ia mengenal tatapan semacam itu."},
				{"text": "Kau berterima kasih dan berkemah lebih jauh.",
				 "good_narr": "Kau tidur singkat tapi aman. Pagi harinya ia sudah pergi, tanpa jejak.",
				 "bad_narr": "Kau berkemah lebih jauh. Kau tak tidur. Kau mendengarkan angin semalaman."},
			]},
		&"wild_herbs": {
			"title": "Tanah lapang. Tanaman-tanaman yang kau kenali — sebagian menyembuhkan, sebagian membunuh.",
			"choices": [
				{"text": "Kau memilah dengan sabar, mengikuti apa yang kau tahu.",
				 "good_narr": "Kau menemukan ramuan yang tepat. Satu luka menutup dengan rapi.",
				 "bad_narr": "Kau mengacaukan dua jenis daun. Kau menyadarinya dari rasanya."},
				{"text": "Kau membiarkan nalurimu memandu tanpa berpikir.",
				 "good_narr": "Kau mengunyah selembar daun. Sesuatu dalam dirimu mereda.",
				 "bad_narr": "Naluri itu bukan milikmu. Kau mengunyah yang seharusnya tidak."},
				{"text": "Kau memetik semuanya, memilah belakangan.",
				 "good_narr": "Kau pergi dengan kantong penuh. Kau akan menemukan gunanya.",
				 "bad_narr": "Memetik butuh waktu. Kau menghabiskan lebih dari yang seharusnya."},
			]},
		&"old_hunter": {
			"title": "Pemburu tua, berjongkok, menunjuk dengan jarinya. \"Babi hutan, dua langkah di sana. Bantu aku atau pergi.\"",
			"choices": [
				{"text": "Kau setuju. Kau berlari menggiringnya.",
				 "good_narr": "Babi hutan itu tumbang. Si pemburu memberimu sepotong daging dan sebilah pisau.",
				 "bad_narr": "Babi hutan itu menyerudukmu. Si pemburu datang terlambat."},
				{"text": "Kau menolak. Kau melanjutkan perjalananmu.",
				 "good_narr": "Kau pergi. Kelak, kau mencium harum daging panggang di belakangmu. Kau tak menyesal.",
				 "bad_narr": "Kau pergi. Si pemburu tak berkata apa-apa. Ia tak lupa."},
				{"text": "Kau malah bertanya apakah ia melihat pengelana lain.",
				 "good_narr": "Ia menceritakan tiga pertemuan. Kini kau tahu siapa saja yang ada di tanah ini.",
				 "bad_narr": "Ia tak mendengarkanmu. Ia menatap semak itu. Ia pergi tanpa menjawab."},
			]},
		&"friendly_raven": {
			"title": "Seekor gagak hinggap di bahumu. Ia tak kabur. Ia menatap matamu.",
			"choices": [
				{"text": "Kau bicara padanya, tenang, seperti pada sesama pengelana.",
				 "good_narr": "Ia menguak tiga kali. Kau memahami setiap kuakan. Kau tahu sesuatu yang baru.",
				 "bad_narr": "Ia terbang tanpa menjawab. Kau bertanya-tanya apa yang akan ia katakan."},
				{"text": "Kau menyodorkan remah beracun untuk menguji.",
				 "good_narr": "Ia menolak. Kau tahu ia lebih bijak darimu. Kau pergi dalam diam.",
				 "bad_narr": "Ia menerima. Ia menelan. Ia menatapmu, lama, sebelum jatuh. Kau membawanya bersamamu."},
				{"text": "Kau mengikutinya saat ia terbang.",
				 "good_narr": "Ia menuntunmu ke jalan pintas. Kau menghemat berjam-jam.",
				 "bad_narr": "Ia membawamu jauh, lalu lenyap. Kau kembali menyusuri jalanmu."},
			]},
		&"sea_cave": {
			"title": "Gua laut. Pasirnya berkilauan — logam, mungkin. Air pasang mulai naik.",
			"choices": [
				{"text": "Kau membenamkan tangan ke dalam pasir.",
				 "good_narr": "Segenggam koin kuno. Dan sebuah cincin yang tak pernah kusam.",
				 "bad_narr": "Sesuatu menggigit tanganmu — kepiting raksasa, bersembunyi."},
				{"text": "Kau menunggu air surut agar bisa melihat lebih jelas.",
				 "good_narr": "Saat air mundur, kau melihat persis apa yang harus diambil.",
				 "bad_narr": "Air pasang berlama-lama. Malam mendapatimu lebih dulu."},
				{"text": "Kau bernyanyi untuk laut sebelum menyentuh apa pun.",
				 "good_narr": "Air mendengarkanmu. Kau pergi terbebas dari satu kutukan dan membawa kerang yang berguna.",
				 "bad_narr": "Air naik lebih cepat dari dugaan. Kau keluar basah kuyup, jantung berdebar."},
			]},
		&"brackish_spring": {
			"title": "Mata air payau. Rasanya memuakkan. Tapi tetap saja air.",
			"choices": [
				{"text": "Kau meminumnya hati-hati, seteguk demi seteguk.",
				 "good_narr": "Dahagamu hilang. Cukup untuk melanjutkan perjalanan.",
				 "bad_narr": "Rasanya bukan sekadar pahit. Kau merasakannya kemudian."},
				{"text": "Kau mengamati apa yang tumbuh di sekitarnya sebelum minum.",
				 "good_narr": "Kau melihat tanda-tanda di bebatuan. Mata airnya lebih murni di hulu.",
				 "bad_narr": "Tak ada yang berguna. Kau memutuskan tak minum. Kau pergi dengan haus."},
				{"text": "Kau mengisi kantong airmu dan pergi.",
				 "good_narr": "Kau punya air untuk dua hari. Itu berharga.",
				 "bad_narr": "Kantong air itu berubah cokelat. Kau menyadarinya terlambat."},
			]},
		&"old_monk": {
			"title": "Rahib tua menyapu ambang batu. Ia menatapmu tanpa heran.",
			"choices": [
				{"text": "Kau memohon berkat darinya.",
				 "good_narr": "Ia meletakkan tangan di dahimu. Sesuatu dalam dirimu menjadi tenang.",
				 "bad_narr": "Ia menolak dengan sopan. \"Simpan ketakutanmu. Mereka berguna bagimu.\""},
				{"text": "Kau meminta minum dan menggeledah selagi ia menjauh.",
				 "good_narr": "Kau menemukan dua keping uang dan sepotong roti. Ia tak menyadari apa pun.",
				 "bad_narr": "Kau mengangkat mata. Ia menatapmu dari ambang pintu. Ia tahu."},
				{"text": "Kau bertanya apa yang ia ketahui tentang tanah ini.",
				 "good_narr": "Ia menceritakan satu abad dalam empat kalimat. Kau lebih paham apa yang menantimu.",
				 "bad_narr": "Ia tersenyum, tak berkata apa-apa. Kau pergi membawa pertanyaan-pertanyaanmu."},
			]},
		&"scholar": {
			"title": "Cendekiawan keliling membuka peti penuh peta, botol, buku. \"Kau cari apa?\"",
			"choices": [
				{"text": "Kau bertanya apa miliknya yang paling berharga.",
				 "good_narr": "Ia menjual peta yang berguna dengan harga murah. Perjalanan berlanjut, lebih siap.",
				 "bad_narr": "Ia menawarkan barang-barang tak berguna. Kau pergi tanpa apa pun."},
				{"text": "Kau menawar sebotol ramuan sambil meyakinkannya kau punya banyak.",
				 "good_narr": "Ia melepasnya hampir cuma-cuma. Kau pergi membawa obat sungguhan.",
				 "bad_narr": "Ia tersinggung. Ia menutup petinya. Kau pergi tanpa apa pun."},
				{"text": "Kau mengajukan pertanyaan ilmiah padanya.",
				 "good_narr": "Ia menjawab panjang lebar. Kau memetik tiga hal berguna darinya.",
				 "bad_narr": "Ia bicara, lama, lama sekali. Tak satu pun kau ingat."},
			]},
		&"lost_child": {
			"title": "Anak tersesat, wajahnya bersih, bertanya di mana rumahnya. Ia menyebut nama sebuah desa.",
			"choices": [
				{"text": "Kau mengatakan yang kau tahu dan mengarahkannya sebisamu.",
				 "good_narr": "Ia berterima kasih. Kelak, keluarganya akan membalasmu.",
				 "bad_narr": "Ia tak memercayaimu. Ia pergi ke arah sebaliknya. Kau tak tahu apa yang menimpanya."},
				{"text": "Kau meminta keterangan lebih sebelum menjawab.",
				 "good_narr": "Ada yang janggal dalam jawabannya. Kau mundur tepat pada waktunya.",
				 "bad_narr": "Kau sadar anak itu tidak ada. Kau pergi cepat."},
				{"text": "Kau menyentuh dahinya, lembut, dalam diam.",
				 "good_narr": "Ia tersenyum, menunjukkan arah. Ia memang anak kecil. Kau sudah lupa bagaimana rasanya.",
				 "bad_narr": "Ia tersenyum. Kulitnya dingin. Kau menarik tangan terlambat."},
			]},
		&"healer_cottage": {
			"title": "Rumah kecil, cerobongnya berasap, harum daun-daun terbakar. Perempuan tua memberi isyarat masuk.",
			"choices": [
				{"text": "Kau masuk dan membayar keahliannya.",
				 "good_narr": "Ia mengobatimu. Kau pergi dengan luka yang menutup.",
				 "bad_narr": "Ia berkata tak bisa berbuat apa-apa untukmu hari ini. Kembalilah besok."},
				{"text": "Kau menuntut diobati tanpa membayar.",
				 "good_narr": "Ia mengobatimu karena takut. Kau pergi utuh, hati nurani sedikit keruh.",
				 "bad_narr": "Ia memang mengobatimu. Tapi ia menambahkan sesuatu. Kau merasakannya, kemudian."},
				{"text": "Kau berlagak anak hilang agar ia mengobatimu cuma-cuma.",
				 "good_narr": "Ia iba. Mengobatimu. Memberimu makan. Kau pergi kenyang.",
				 "bad_narr": "Ia melihat tembus sandiwaramu. Kuah yang ia sodorkan bukan seperti yang ia katakan."},
			]},
		&"mirror_lake": {
			"title": "Danau yang rata sempurna memantulkan langit yang bukan langit di atasmu.",
			"choices": [
				{"text": "Kau membungkuk untuk melihat langit di bawah.",
				 "good_narr": "Kau melihat bintang-bintang yang tak dikenal siapa pun di atas. Kau menghafal satu.",
				 "bad_narr": "Sebuah bintang menatapmu. Kau merasa ia mengikutimu, mulai sekarang."},
				{"text": "Kau membenamkan tangan ke dalam pantulan langit.",
				 "good_narr": "Kau menariknya keluar dengan segenggam malam. Itu akan berguna.",
				 "bad_narr": "Sebuah tangan menangkapmu dari bawah. Kau melepaskan diri, tapi sesuatu tertinggal di pergelanganmu."},
				{"text": "Kau pergi tanpa memandang lebih jauh.",
				 "good_narr": "Kau belajar bahwa menolak tahu juga bisa. Itu sebuah kekuatan.",
				 "bad_narr": "Kau pergi. Tapi malam berikutnya kau memimpikan langit di bawah."},
			]},
		&"glowing_fungi": {
			"title": "Lingkaran jamur biru, bercahaya. Mereka berdenyut pelan, serentak.",
			"choices": [
				{"text": "Kau memetik satu untuk memeriksanya.",
				 "good_narr": "Cahayanya membantumu melihat dalam gelap. Kau pergi membawa lentera hidup.",
				 "bad_narr": "Kau menghirup sporanya saat membungkuk. Kau baru sadar setelahnya."},
				{"text": "Kau menari pelan-pelan di dalam lingkaran.",
				 "good_narr": "Lingkaran itu menerima langkahmu. Sebuah kutukan larut dalam cahaya.",
				 "bad_narr": "Lingkaran itu menutup di sekelilingmu sesaat. Kau keluar dengan tanda."},
				{"text": "Kau memutarinya tanpa masuk.",
				 "good_narr": "Kau pergi. Satu spora tetap mengikutimu — yang baik.",
				 "bad_narr": "Kau pergi. Kau takkan pernah tahu apa yang ada di sisi seberang."},
			]},
		&"wind_harp": {
			"title": "Harpa tergantung di antara dua batu karang. Angin memainkannya begitu lama hingga senar-senarnya berkilau.",
			"choices": [
				{"text": "Kau menyelaraskan suaramu dengan nadanya.",
				 "good_narr": "Kau mempelajari lagu yang tak pernah kau tahu. Ia akan berguna untuk menenangkan.",
				 "bad_narr": "Kau bernyanyi terlalu lama. Angin telah mengurasmu."},
				{"text": "Kau mengambil harpa itu.",
				 "good_narr": "Berat tapi berguna. Kau pergi membawa alat musik yang bernyanyi sendiri.",
				 "bad_narr": "Senar-senarnya menyayatmu. Saat kau menarik, mereka menarik balik."},
				{"text": "Kau berterima kasih pada angin dengan suara keras dan pergi.",
				 "good_narr": "Angin sepoi menemanimu kemudian, berjam-jam. Kau berjalan tanpa takut.",
				 "bad_narr": "Angin tak menjawab. Kau pergi tanpa apa pun."},
			]},
		&"sailor_grave": {
			"title": "Salib kayu tertancap di pasir. Sebuah nama terukir, hampir terhapus. Di sampingnya sebuah botol, masih tersegel.",
			"choices": [
				{"text": "Kau mengucapkan nama itu keras-keras agar ia disebut sekali lagi.",
				 "good_narr": "Kau pergi dengan damai. Sesuatu mengikutimu, penuh kebaikan, sampai wilayah berikutnya.",
				 "bad_narr": "Kau mengucapkan nama itu. Tak terjadi apa-apa. Kau pergi."},
				{"text": "Kau membuka botol itu.",
				 "good_narr": "Sebuah pesan — peta harta sepelemparan batu dari sini. Kau menemukan beberapa keping uang.",
				 "bad_narr": "Pesan yang kosong. Dan aroma yang takkan pernah kau lupakan."},
				{"text": "Kau mencabut salib itu untuk melihat apakah ada sesuatu di bawahnya.",
				 "good_narr": "Kotak berkarat. Di dalamnya, sebilah pisau. Alat yang bagus.",
				 "bad_narr": "Ada tulang-belulang, lalu sesuatu yang sejak itu mengikutimu setengah langkah di belakang."},
			]},
		&"star_map": {
			"title": "Di atas lempeng batu, gambar yang presisi — itu langit. Tapi langit dari masa yang sangat lampau.",
			"choices": [
				{"text": "Kau membandingkannya dengan yang kau lihat di atasmu.",
				 "good_narr": "Kau menemukan tiga bintang yang telah berubah. Kau mengerti apa artinya.",
				 "bad_narr": "Kau menengadah, lama. Kau tak menemukan apa pun yang berguna."},
				{"text": "Kau menelusuri garis-garisnya dengan jarimu.",
				 "good_narr": "Sebuah peta muncul dalam benakmu. Kau akan bisa menemukan tempat ini lagi.",
				 "bad_narr": "Satu garis menjalar ke tanganmu. Sejak itu kau membawanya."},
				{"text": "Kau menghapus sebagian untuk mengecoh orang berikutnya.",
				 "good_narr": "Kesenangan kecil, keuntungan nyata. Kau pergi sambil tersenyum.",
				 "bad_narr": "Batu itu mengatup saat kau sentuh. Kau menarik tangan dengan sebuah tanda."},
			]},
		&"burning_pyre": {
			"title": "Tumpukan kayu bakar berasap. Seseorang — di atasnya. Tak ada orang lain di sekitar.",
			"choices": [
				{"text": "Kau memadamkan api dengan tanah.",
				 "good_narr": "Kau menyelamatkan seseorang, mungkin. Ia kabur tanpa sepatah kata. Kau menemukan uang di abu.",
				 "bad_narr": "Api mencabik tanganmu. Orang itu tak pernah bangkit."},
				{"text": "Kau berdoa untuk yang terbakar.",
				 "good_narr": "Kau berdoa. Kedamaian datang. Api itu padam sendiri, tak lama kemudian.",
				 "bad_narr": "Kau berdoa. Sesuatu mendengarkanmu. Bukan yang kau kira."},
				{"text": "Kau pergi cepat. Ini bukan kisahmu.",
				 "good_narr": "Kau pergi. Asap menjauh. Kau cepat melupakannya.",
				 "bad_narr": "Kau pergi. Kau merasakan tatapan seseorang dari dalam api. Kau mempercepat langkah."},
			]},
		&"frozen_tower": {
			"title": "Menara yang utuh, terbungkus es di tengah musim panas. Sebuah pintu terbuka di puncaknya.",
			"choices": [
				{"text": "Kau memanjat.",
				 "good_narr": "Di puncak, sebuah buku terbuka. Kau membaca tiga halaman. Kau akan keluar sebagai orang yang berubah.",
				 "bad_narr": "Panjatannya lebih panjang dari kelihatannya. Kau turun tanpa apa pun."},
				{"text": "Kau meletakkan tangan di atas es dan bicara padanya.",
				 "good_narr": "Es itu mendengarkanmu. Ia mengambil satu kutukan dan menyimpannya untukmu.",
				 "bad_narr": "Es itu mendengarkanmu. Dan mengembalikan sesuatu yang lupa kau hilangkan."},
				{"text": "Kau memutarinya, waspada.",
				 "good_narr": "Kau menemukan pintu jebakan di tanah. Di dalamnya, pecahan yang menarik.",
				 "bad_narr": "Kau menemukan tiga jejak mengitari menara. Semuanya masuk ke dalam. Tak satu pun keluar."},
			]},
		&"underwater_shadow": {
			"title": "Bayangan bergerak di bawah air, perlahan, hanya beberapa meter jauhnya. Ia tak pernah naik.",
			"choices": [
				{"text": "Kau menjauh dari tepian tanpa berlari.",
				 "good_narr": "Kau pergi. Bayangan itu mengikutimu sebentar, lalu menyerah.",
				 "bad_narr": "Bayangan itu mengikutimu lama. Kau berjalan tanpa henti, jantung menegang."},
				{"text": "Kau melempar kerikil untuk menyapanya.",
				 "good_narr": "Ia melontarkan kerikil itu keluar dari air. Kau memungutnya. Kerikil itu telah berubah.",
				 "bad_narr": "Ia tak mengembalikan kerikil itu. Ia naik, perlahan, ke permukaan. Kau pergi tanpa menoleh."},
				{"text": "Kau membisikkan kata purba pada air.",
				 "good_narr": "Bayangan itu berhenti. Ia mendengarkan. Ia menitipkan sesuatu padamu, dalam keheningan.",
				 "bad_narr": "Bayangan itu berhenti. Ia mendengarkanmu. Terlalu saksama."},
			]},
		&"lit_shrine": {
			"title": "Altar yang baru saja diterangi. Seseorang lewat belum lama ini.",
			"choices": [
				{"text": "Kau meletakkan sekeping uang dan membisikkan doa.",
				 "good_narr": "Kehangatan menyelimutimu. Kau pergi dengan luka yang menutup.",
				 "bad_narr": "Kau pergi. Tak terjadi apa-apa. Tapi sesuatu telah ditenangkan."},
				{"text": "Kau menyalakan kembali lilinnya sambil mengambil keping uang itu.",
				 "good_narr": "Kau pergi membawa uang itu dan hati yang tenang.",
				 "bad_narr": "Keping itu membakar di dalam sakumu, lama."},
				{"text": "Kau menambahkan sejumput rambutmu pada lilin itu.",
				 "good_narr": "Kau pergi membawa pengetahuan yang tadinya tak ada.",
				 "bad_narr": "Yang kau tinggalkan di sana lebih dari sekadar rambut. Kau akan merasakannya."},
			]},
		&"tired_soldier": {
			"title": "Prajurit duduk di atas debu, pedangnya yang patah tergeletak di samping. \"Kau tahu di mana aku bisa tidur?\"",
			"choices": [
				{"text": "Kau menunjukkan sudut tenang yang sempat kau lihat.",
				 "good_narr": "Ia berterima kasih dan membagikan rahasia medan perang — berguna.",
				 "bad_narr": "Ia tak memercayaimu. Ia memunggungimu."},
				{"text": "Kau mengambil pedang patahnya dan pergi.",
				 "good_narr": "Ia tak berkata apa-apa. Bilah itu ternyata tak sepatah kelihatannya.",
				 "bad_narr": "Ia lebih cepat dari kelihatannya. Bilah patah itu menemukan sasarannya."},
				{"text": "Kau memberi isyarat dan pergi tanpa bicara.",
				 "good_narr": "Kau pergi. Ia tertidur di tempatnya.",
				 "bad_narr": "Ia mengikutimu dengan tatapan. Kau mempercepat langkah."},
			]},
		&"glowing_chest": {
			"title": "Peti kecil yang berdenyut lembut menembus papan-papannya. Ia tampak hidup.",
			"choices": [
				{"text": "Kau membukanya dengan tenang.",
				 "good_narr": "Di dalamnya, pecahan yang berharga. Kau menyelipkannya ke saku.",
				 "bad_narr": "Di dalamnya, uap. Kau menghirup satu embusan."},
				{"text": "Kau menghancurkannya dengan satu tendangan.",
				 "good_narr": "Kau mendapatkan sekeping uang bagus dan sebongkah kristal.",
				 "bad_narr": "Sebuah serpihan menyayat tulang keringmu."},
				{"text": "Kau meletakkan tangan dan mendengarkan apa yang ingin ia katakan.",
				 "good_narr": "Peti itu menyerap sesuatu dari dalam dirimu. Kau pergi lebih ringan.",
				 "bad_narr": "Peti itu memindahkan apa yang ia bawa. Kini kaulah yang membawanya."},
			]},
		&"blood_fruit": {
			"title": "Buah semerah darah bergantung di pohon yang sudah mati. Baunya masih segar.",
			"choices": [
				{"text": "Kau memakannya mentah-mentah.",
				 "good_narr": "Sarinya manis dan mengenyangkan. Kau pergi dengan tenaga baru.",
				 "bad_narr": "Awalnya manis, lalu pahit. Sangat pahit."},
				{"text": "Kau memetiknya dan menyimpannya untuk nanti.",
				 "good_narr": "Kau menyimpannya. Ia tak membusuk. Pertanda baik.",
				 "bad_narr": "Ia meleleh di antara jari-jarimu. Kau pergi tanpa apa pun."},
				{"text": "Kau meninggalkannya sebagai persembahan di pohon itu.",
				 "good_narr": "Pohon itu bergetar. Kau menerima sebuah kata purba sebagai balasan.",
				 "bad_narr": "Kau pergi. Pohon itu tak berkata apa-apa. Buah itu membusuk di belakangmu."},
			]},
		&"wandering_horse": {
			"title": "Kuda berpelana merumput dengan tenang, tanpa penunggang. Ia menatapmu tanpa takut.",
			"choices": [
				{"text": "Kau bicara lembut dan menuntunnya lewat tali kekang.",
				 "good_narr": "Ia mengikutimu. Kau melintasi wilayah ini jauh lebih cepat.",
				 "bad_narr": "Ia menjauh saat kau mendekat. Ia tak menginginkanmu."},
				{"text": "Kau menungganginya dengan paksa.",
				 "good_narr": "Kau berhasil. Ia menerima kuasamu. Kau pergi di atas punggungnya.",
				 "bad_narr": "Ia melemparmu ke tanah. Sesuatu di lenganmu patah."},
				{"text": "Kau memutarinya untuk melihat apa yang ia makan.",
				 "good_narr": "Kau menemukan sisa-sisa penunggangnya — dan apa yang ia bawa.",
				 "bad_narr": "Kau tak menemukan apa pun. Kuda itu menatapmu, kesal."},
			]},
		&"burning_scroll": {
			"title": "Gulungan perkamen menyala yang tak kunjung habis terbakar. Ia melayang setinggi manusia.",
			"choices": [
				{"text": "Kau mengucapkan kata yang ia nantikan.",
				 "good_narr": "Ia padam dan jatuh ke tanganmu. Kau bisa membacanya.",
				 "bad_narr": "Kau telah mengucapkan kata itu. Tapi bukan yang ia nantikan."},
				{"text": "Kau mencoba membacanya menembus nyala api.",
				 "good_narr": "Kau mengingat tiga kata. Kelak mereka berguna.",
				 "bad_narr": "Api membakar matamu. Kau pergi sambil menangis."},
				{"text": "Kau menyambarnya meski api menyala.",
				 "good_narr": "Kau menahan rasa terbakar. Perkamen itu milikmu.",
				 "bad_narr": "Api itu menolak padam. Kau melepaskannya sambil menjerit."},
			]},
		&"whispering_wind": {
			"title": "Angin bicara padamu dengan jelas. Tiga kata, perlahan. Ia meminta sesuatu darimu.",
			"choices": [
				{"text": "Kau menjawab dengan suara keras.",
				 "good_narr": "Angin itu lalu menemanimu, lembut, untuk waktu yang lama.",
				 "bad_narr": "Angin memutus suaramu. Kau pergi sebelum selesai bicara."},
				{"text": "Kau menyanyikan satu nada saja sebagai jawaban.",
				 "good_narr": "Angin menggendongmu. Tenagamu pulih tanpa upaya.",
				 "bad_narr": "Nadanya sumbang. Angin mengulang nadanya sendiri, lebih keras."},
				{"text": "Kau membisu dan menunggu ia berlalu.",
				 "good_narr": "Kau menunggu. Angin akhirnya menjauh. Kau pergi.",
				 "bad_narr": "Angin tak berhenti. Kau berjalan melawannya, lama."},
			]},
		&"wounded_animal": {
			"title": "Rusa tergeletak, anak panah menancap di lambungnya. Ia masih bernapas.",
			"choices": [
				{"text": "Kau mencabut anak panah itu dengan lembut.",
				 "good_narr": "Ia bangkit, lemah, menitipkan satu tatapan sebelum kabur. Kelak, kau menemukan tanduk rusa yang berguna di jalanmu.",
				 "bad_narr": "Ia meronta. Batang panah itu menggores tanganmu."},
				{"text": "Kau menghabisinya dengan satu pukulan bersih.",
				 "good_narr": "Kau makan dengan layak. Kau pergi kenyang.",
				 "bad_narr": "Ia menatapmu saat kau memukul. Tidurmu takkan pernah sama lagi."},
				{"text": "Kau meletakkan tangan dan mengambil sebagian rasa sakitnya.",
				 "good_narr": "Ia bangkit. Kau merasakan namanya di kepalamu. Kini kau bisa memanggilnya.",
				 "bad_narr": "Kau mengambil terlalu banyak. Kau terhuyung."},
			]},
		&"old_well_treasure": {
			"title": "Sumur yang mengering. Di dasarnya, logam berkilau samar. Batunya rapuh.",
			"choices": [
				{"text": "Kau turun dengan paksa, tanpa tali.",
				 "good_narr": "Kau naik membawa segenggam koin dan cincin berukir.",
				 "bad_narr": "Kau tergelincir. Lenganmu membentur batu. Kau memanjat naik sendirian, susah payah."},
				{"text": "Kau mencari tali dan turun dengan hati-hati.",
				 "good_narr": "Kau naik tanpa cedera membawa apa yang kau inginkan.",
				 "bad_narr": "Turunnya makan waktu berjam-jam. Kau naik dengan tenaga terkuras."},
				{"text": "Kau pura-pura pergi dan kembali saat senja turun.",
				 "good_narr": "Lebih mudah dalam gelap. Kau pergi membawa dua keping lebih banyak.",
				 "bad_narr": "Sumur itu lebih dalam di malam hari. Kau pergi tanpa apa pun."},
			]},
	}
